name: Parallel_Workflow

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # Adjust batch numbers as needed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Chrome & Driver
        run: |
          choco install googlechrome --ignore-checksums --no-progress
          choco install chromedriver --no-progress
        shell: cmd

      - name: Run Test Execution for Batch ${{ matrix.batch }}
        run: |
          cd ${{ github.workspace }}
          Run.bat -run -project_location "Projects\\GTS_Dynamic" -release "Tinder" -testset "Tinder${{ matrix.batch }}"
        shell: cmd
